### ISSUE TITLE
Outdated changelog on WordPress.org

### ISSUE THREAD

**Issue by coccoinomane** [crisp-im/crisp-plugin-wordpress#5]
Hello,

The plugin's version is v0.21, but the changelog on WordPress.org covers up to v0.5 (screenshot: https://d.pr/i/6z8gjv).

This means that when updating the plugin on our clients websites, we do not know what we are doing.

Could you please keep the changelog up to date with the actual version?

Thank you,
Guido

**Comment by baptistejamin** [comment]
It's now updated!

**Comment by coccoinomane** [comment]
Thank you very much! I can now see the complete changelog.
Have a nice day,
Guido
